name: Prebuild Binaries and Publish

on:
  push:
    branches:
      - main


jobs:
  prebuild-linux:
    name: Prebuild Binaries for Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Setup Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -y -qq
          sudo apt-get install -y g++-multilib gcc-multilib libcups2-dev libcups2-dev:i386 libc6-dev-i386 linux-libc-dev linux-libc-dev:i386 libgcc-s1:i386 libstdc++6:i386
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v1
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- --strip --target 26.0.0 --runtime electron --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- --strip --target 18.16.1 --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
  prebuild-macos:
    name: Prebuild Binaries for macOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v1
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- --strip --target 18.16.1 --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
  prebuild-windows:
    name: Prebuild Binaries for Windows
    runs-on: windows-2019
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v1
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- --strip --target 26.0.0 --runtime electron --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- --strip --target 18.16.1 --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
